# Source: https://github.com/marketplace/actions/build-and-release-apk

name: Android CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: ./SimpleFrame
      run: chmod +x gradlew
      
    - name: Build with Gradle
      working-directory: ./SimpleFrame
      run: ./gradlew assembleRelease
    
    - name: Upload apk to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./SimpleFrame/app/build/outputs/apk/release/**.apk)
        asset_name: com.louissimonmcnicoll.simpleframe
        tag: ${{ github.ref }}
        overwrite: true
